on:
    push:
        branches:
            - main

name: Render Website

jobs:
    checkout-and-deploy:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main
              
            - name: Render to markdown
              run: |
                mkdir -p rendered
                cd renderer
                make
                ./gorender -ff ../content ../output

            - name: Commit and push changes
              uses: Cecilapp/GitHub-Pages-deploy@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                email: ${{ secrets.EMAIL }}
                build_dir: output/
                branch: gh-pages
